### ISSUE TITLE
how to set email as an icon

### ISSUE THREAD

**Issue by tinasoul** [techpeace/personal-site-template#10]
in config

set :email, "tinapshah@gmail.com"?

**Comment by techpeace** [comment]
It's actually:

``` ruby
set :gravatar_email_address, "me@adalovelace.com"
```

...where the email address is one that you have set up to use with [Gravatar](http://gravatar.com). Let me know if that works for you.

**Comment by tinasoul** [comment]
ok have the gravtar email set already....this pulls in the gravtar

want a mail icon to show up in the nav...like this http://withwarmth.tumblr.com/abouttinapshah

html would be something like this on a normal site just wondering what to do in middleman

<a href="mailto:tina@snapshotindia.com" target="blank"><i class="icon-envelope"></i></a>

**Comment by techpeace** [comment]
Oh okay, so that isn't actually implemented. I only have support for the social networks listed there in `config.rb`. It'd be easy to add it yourself, though:

https://github.com/makersquare/personal-site-template/blob/master/source/layouts/layout.erb#L52

There I'm calling the `social_network_link` helper method. You could add support for email address icons to that method:

https://github.com/makersquare/personal-site-template/blob/master/config.rb#L135-L147

Middleman is just static HTML with Rails niceties like templating, partials, and the asset pipeline. It's easy to add straight HTML to a Middleman site, and [the docs](http://middlemanapp.com/) are super-helpful. If you're working on a static site, Middleman is definitely the way to go.

If you add support for a new icon, be sure to open a pull request! Thanks. :smile:
